### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by harumasa-iino** [harumasa-iino/portfolio#123]
## 各種情報
サービス名
Frame Select

URL
https://frame-select.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 部屋の写真アップロード機能
- [ ] 壁検出機能
- [x] ポスター/絵画データベース
- [x] ポスター検索・フィルター機能
- [x] ポスター/絵画表示・配置機能

## READMEレビュー時から変更した機能
削除
- [ ] 壁検出機能

追加
- [ ] 会員登録
- [ ] Google APIを使った認証機能

## サービスイメージがわかるようなスクリーンショット等
レスポンシブにしていますが撮影が必要なため基本的にはスマホでの利用を想定しています
### 表
トップ
<img width="200" alt="image" src="https://github.com/harumasa-iino/portfolio/assets/139933050/92aeff7e-0efa-41a8-8a0e-fa0b67054e59">
インテリアアップロード
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/95d0a82d-cd9a-483f-8298-6dd0c72eafba">
アップロード結果＆ポスター選択画面（一部機能は本リリース）
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/6b7fb969-bfb7-4535-bb6f-f7ef4ec5f075">
設問
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/9c2e8037-3c65-4fd6-8f0a-58b1dbcc30a0">
マッチした結果（マッチしたポスターが複数あれば複数表示）
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/aaecddec-d8ad-4384-b79e-eee50a2dc0d4">
好みの合成画像選択後
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/53e4fbe0-8f9f-4b05-adaf-a8d1bb2049ca">
ポスターの詳細
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/44f353de-577c-4a19-9708-92821094fc0a">
会員登録
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/588e4095-d685-4f21-86ff-287527a61025">
マイページ
<img width="200" src="https://github.com/harumasa-iino/portfolio/assets/139933050/9c1e0899-8630-4455-872f-ccdfcdc28963">

### 管理画面
ポスターデータ一覧
<img width="500" alt="image" src="https://github.com/harumasa-iino/portfolio/assets/139933050/51218ee7-8348-4305-8d21-3a2298587528">
ポスター詳細画面
<img width="500" alt="image" src="https://github.com/harumasa-iino/portfolio/assets/139933050/69bb6b63-c0a5-4e84-8b95-71af52f9a80e">
ポスターのフィルタリング結果
<img width="500" alt="image" src="https://github.com/harumasa-iino/portfolio/assets/139933050/675c5b6b-0b99-479c-8b55-f341af6d4527">

**Comment by kenchasonakai** [comment]
画像のアップロードが出来ませんでしたのでご確認お願いします
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/702325bf27d6aa3cb9c4c1b8544a6234.gif)](https://startup-technology.gyazo.com/702325bf27d6aa3cb9c4c1b8544a6234)

**Comment by harumasa-iino** [comment]
こちらアプリ問題ではなくおそらくChromeのアップデートによるものかと思われますmm
私の方でもデプロイ後同じ症状になりましたが現在は正常に動いております。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
