### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by harumasa-iino** [harumasa-iino/portfolio#6]
### 実装予定の機能
- [ ] 部屋の写真アップロード機能
- [ ] 壁検出機能
- [ ] ポスター/絵画データベース
- [ ] ポスター検索・フィルター機能
- [ ] ポスター/絵画表示・配置機能

・本リリース対応
- [ ] 購入リンク付加
- [ ] 部屋の色認識機能
- [ ] ポスターの色認識機能
- [ ] 色合いマッチングアルゴリズム
- [ ] AR機能で実際の部屋にポスターをマッピング

### 開発方針
Google Vision AIを使用して壁を検出
Canvasを使ってアップロード画像に絵画データを合成
部屋の色認識機能。ポスターの色認識機能もVision AIを使用
実際の部屋にポスターをマッピングするのはAR.jsを使用

### 必要なページ
- [ ] トップページ
- [ ] 画像アップロード画面
- [ ] 機能選択画面
- [ ] 質問画面
- [ ] アップロードされた画像と絵画・ポスターの合成写真
- [ ] ポスター詳細画面
- [ ] AR画面
- [ ] 問い合わせ画面

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

細かく記載されているのは良いかと思いました。
ストーリーポイント5のものはおそらく不安なissueも多いかと思うので、1,2くらいになるくらいまでもう少し細かく分解しておきましょう。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
卒業試験 ER図の試験でまだLGTMが出ていないようですので、そちらの試験でLGTM取得後、再度提出をおねがいします。

**Comment by tmtkzk0823** [comment]
LGTMです。
